### ISSUE TITLE
[FEATURE REQUEST] Open minimized on Startup

### ISSUE THREAD

**Issue by MarcosKlender** [rivafarabi/deckboard#625] opened 2020-12-29 02:37 UTC
**Is your feature request related to a problem? Please describe.**
It is not related to a problem but it's an useful feature.

**Describe the solution you'd like**
Start Deckboard minimized when Windows starts.

**Describe alternatives you've considered**
An option in General Settings called "Open Minimized" near the "Open on Startup" feature. 

**Additional context**
Please. (:

**Comment by rZiMiZ** [comment] 2021-06-30 12:54
Haahaha, oh yeah!

**Comment by ZantsuRocks** [comment] 2022-09-05 18:35
Duplicate of #24

**Closed** 2024-07-22 22:50 UTC
Labels: feature request
