### ISSUE TITLE
Keyboard - 'Run On' not working

### ISSUE THREAD

**Issue by Revenger** [rivafarabi/deckboard#59] opened 2018-11-27 12:32 UTC
On my media center a month back I setup a shortcut 'Alt F4' to close the window and assigned it to 'Media Player Classic Home Cinema' so it would only affect that program but it didn't work.
However it worked without the 'Run On' field filled in.

I just set it up as a panel for shortcuts for the game Elder Scrolls Online and when I used 'Run On' my hotkeys didn't work.
Same thing as first removing 'Run On' the shortcuts work.

So there may be a problem with the 'Run On' hook to assign commands to be sent to a specific application.

My Razer Synapse has a program hook which works fine for my mouse for setting custom button mappings.

**Comment by Nenniana** [comment] 2019-02-07 17:38
I am having the same problem with the 'Run on' function. No matter the software designated, the command seems to not work - removing the 'Run on' parameter makes the macro work.

**Comment by lucaswunder** [comment] 2020-05-12 19:55
The "run on" is not working.

**Comment by digitalfiz** [comment] 2020-05-20 17:11
I can confirm this also

**Comment by lucaswunder** [comment] 2020-05-21 12:12
After spending some time on this, I come out that, for some reason, my user on windows 10, not allow the Deck board app to view the running process.
To workaround with this, I create a new Windows 10 user and install the latest version of DeckBoard desktop in this session. 
After that, I get back to my current user, open the Deckboard app from the folder of the new user and that's works.

**Comment by rivafarabi** [comment] 2024-05-04 09:34
Closing this, due to "Run On..." option will be deprecated in the future release of version 3 of the app.

**Closed by rivafarabi** 2024-05-04 09:34 UTC
