### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Fenwick17** [rivafarabi/deckboard#87] opened 2018-12-28 12:33 UTC
Having some issues trying to get this all working with Linux.  
Provided my IP address to the App, but says it can't connect.  
The Windows app does run with wine (gets a JS error though) but can't really do much with it, for example you click add board, and type in the details then click add. But the board does not actually get created

**Comment by rivafarabi** [comment] 2018-12-28 19:32
I currently work on several features right now, so haven't touch the linux side for a while.  Pre-release version for linux expected around February - March. Thanks for your patient

**Comment by DarkJarris** [comment] 2019-01-25 22:21
Leaving in a +1 for Linux version.

**Comment by jusdepatate** [comment] 2019-02-23 07:07
+1

**Comment by rafagouveia** [comment] 2019-02-25 18:37
+1

**Comment by edouardmenayde** [comment] 2019-03-07 18:21
+1 (i'm considering buying the app but Linux support is a must have for me)

**Comment by rivafarabi** [comment] 2019-03-09 01:35
![ubuntu](https://user-images.githubusercontent.com/4427494/54064371-3b353f00-4246-11e9-8e55-95a2f0187045.PNG)

If the development goes well, It will be released in the end of this month :)

**Comment by rafagouveia** [comment] 2019-03-09 02:13
@rivafarabi What great news, I look forward to enjoying the **linux version**.
Congratulations on the great work.

**Comment by v-glb** [comment] 2019-04-10 09:12
Hi there,

how's the Linux development going? Really looking forward to it. =) Thanks for your great work!

**Comment by rivafarabi** [comment] 2019-04-10 09:16
Because of unfortunate circumstances occured last month, the development
will be continued starting next week along with anticipated multiaction
feature. Sorry for waiting for so long.

**Comment by v-glb** [comment] 2019-05-21 18:18
Hey there,

no worries! It's done when it's done. =)
Any news on the development? I'm using Ubuntu 18.04 as my main OS btw, so if I can be of any help with testing deckboard on Linux feel free to contact me.

**Comment by calvinwankhede** [comment] 2019-06-01 09:49
Another Arch user looking for Linux support. Thank you for the app.

**Comment by chabad360** [comment] 2019-07-15 18:02
Any updates on the linux version? I'm quite excited for that, and would be glad to help test if you need it.

**Comment by TheCynicalLiger** [comment] 2019-07-28 11:31
@rivafarabi any update on linux support yet mate?

**Comment by tarbear123** [comment] 2019-10-05 05:15
Any updates on the linux version? I'm quite excited for that

**Comment by pimgux** [comment] 2019-10-15 20:15
Hello, the version for Linux would be very good, Very good work.
Regards

**Comment by sergiovitor** [comment] 2019-10-21 18:53
Any news about linux version?

**Comment by MaBeuLux88** [comment] 2019-11-04 20:00
+1 for the linux support. Debian testing (Bullseye) user here.

**Comment by pascoual** [comment] 2019-12-20 22:44
+1 for the linux support.

**Comment by odiegoduarte** [comment] 2020-01-25 14:35
Hello, do you still mean to release a version for linux?

**Comment by cfanoulis** [comment] 2020-02-29 09:32
has anyone managed to run this under wine? does it work?

**Comment by chabad360** [comment] 2020-03-01 20:51
> has anyone managed to run this under wine? does it work?

Running under wine I don't think is an issue, the problem is that from wine I don't believe it's really possible to interface with the rest of the system properly.

**Comment by digitalfiz** [comment] 2020-03-02 03:18
It's electron so technically building it for linux or mac is super simple but again interfacing with the rest of the system is the hard part.

**Comment by TheCynicalLiger** [comment] 2020-06-18 15:21
if he was to build a linux version or even open source the code for the linux version i would maintain a arch linux repo :)

**Comment by luccacondratiuk** [comment] 2020-07-23 15:06
+1 for linux support!!
Any updates?

**Comment by billyjbryant** [comment] 2020-08-08 17:03
Still no proper linux support, it runs in Wine but since the electron app doesn't draw a close button, you have to forcefully quit it, and this locks the TCP port in wine. Would LOVE to see this ported to Linux :|

**Comment by maximoosemine** [comment] 2020-08-18 00:23
+1 for linux support.

**Comment by JorgeOsorio97** [comment] 2020-08-26 14:20
+1

**Comment by Raustone** [comment] 2020-08-28 17:15
+1 for linux suport ! And if linux support come, I gonna pay de pro version.

**Comment by digitalfiz** [comment] 2020-08-29 04:59
@rivafarabi looks like you got a decent amount of interest in this and plenty of people to test. I definitely be willing to test and give back detailed information.

**Closed** 2022-10-12 15:16 UTC
