### ISSUE TITLE
[BUG] (Mobile edition) I get an error when using multiple buttons more second per board which says i don't have pro when i do

### ISSUE THREAD

**Issue by Neopopulas** [rivafarabi/deckboard#1045] opened 2024-02-10 11:24 UTC
**Describe the bug**
When using the new Advanced Board. Create a single button in the top-right board and a single button on the top-left board and you will get an error

**To Reproduce**
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows 11
 - Version: 3.0.0-rc5

**Client App (please complete the following information):**
 - OS: Android 13
 - Version: 3.0.4 (pro)

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by rivafarabi** [comment] 2024-02-10 12:57
Do you have any screenshot or screen capture video showing the bug?

**Comment by Neopopulas** [comment] 2024-02-10 13:46
Sure can. This is what it looks like. I double-checked and the app i have
on mobile is pro, and the server version was just recently updated since it
said there was an update pending.
[image: 20231028_2234234.jpg]

**Comment by Neopopulas** [comment] 2024-02-10 13:49
![20231028_2234234](https://github.com/rivafarabi/deckboard/assets/60027182/7fb01447-bd07-4e19-9d91-0720ac36a620)

**Comment by rivafarabi** [comment] 2024-02-11 04:56
Thanks for the feedback. Will patch it asap

**Comment by Neopopulas** [comment] 2024-02-11 06:33
Fantastic!

**Comment by rivafarabi** [comment] 2024-02-11 18:13
The fix for this issue is included in the latest beta version 3.0.5

Let me know if the issue is still persist by creating a new ticket. Thank you

**Closed by rivafarabi** 2024-02-11 18:13 UTC
Labels: bug
