### ISSUE TITLE
Cannot select OBS scenes

### ISSUE THREAD

**Issue by Purkinjee** [rivafarabi/deckboard#495] opened 2020-08-28 22:58 UTC
In the latest update (1.9.61) I am unable to create new buttons or edit existing buttons that control OBS scenes. OBS is running and connected, however the list of scenes always shows "null". Existing buttons work but are not are unable to be modified.

![newbutton](https://user-images.githubusercontent.com/59910980/91621228-3b982d00-e947-11ea-88ce-9a78691cc284.png)

**Comment by rivafarabi** [comment] 2020-08-29 07:19
Duplicate of #478

**Closed by rivafarabi** 2020-08-29 07:19 UTC
