### ISSUE TITLE
[REQUEST] voicemeter extention

### ISSUE THREAD

**Issue by firefloc** [rivafarabi/deckboard#288] opened 2019-10-21 11:15 UTC
can you make an deckboard extention to control voicemetter potato ?
an api can be found here https://www.vb-audio.com/Services/developers.htm
a lot of streamer use this virtual mix table I think it can be very usefull

**Comment by Yurlyn** [comment] 2019-10-21 11:30
That'd be interesting! For now you could potentially use this maybe: https://github.com/gbevin/SendMIDI

I'm gonna see if I can set this up for myself as well. I'll keep you updated if I can get this to work.

**Comment by derMiepz** [comment] 2019-10-24 12:26
I'd say this is a duplicate of https://github.com/rivafarabi/deckboard/issues/253

**Comment by rivafarabi** [comment] 2020-02-21 19:11
please check this [extension](https://github.com/rivafarabi/voicemeeter-control)

**Closed by rivafarabi** 2020-02-21 19:11 UTC
