### ISSUE TITLE
Ctrl gets stuck when used with multi actions

### ISSUE THREAD

**Issue by LilJur** [rivafarabi/deckboard#522] opened 2020-10-06 18:08 UTC
So I have multi actions set up for my scenes. It uses my macro keys from my VoiceMeeter.
Basically, everything is set up like this; the num # unmutes ctrl+num # mutes.

As a single action, they work fine. I can toggle my mic or game sound on and off without issues. But when I need to use a multi action which contains a macro with ctrl, ctrl gets stuck
For example, when I change from my gameplay scene to my chat scene, the multi action has the macro 'ctrl+num 2' to mute my game audio and 'num 4' to unmute my music.
When I use such a multi action, ctrl gets toggled instead of a simple short press. Which brings a number of issues. One of them being I can't use any of the other scene changes since it will register all the macros as 'Ctrl + key'.
I tried Shift and it has the same issue.

My current solution is to simply change the 'ctrl' macros to single key press macros. But it is not as convenient.

**Comment by Chew0n1t** [comment] 2020-10-10 13:57
Have you tried adding a multiaction step to toggle the ctrl again. This is only a thought but if the ctrl is being toggled when used like this then adding a step to send ctrl to the same app should toggle it back off in theory.

**Comment by SirBashchen** [comment] 2020-12-10 04:44
Same issue exclusive to multi-action, Also affecting command (win), enter and I presume other buttons that aren't alphabetical or numerical.
Tried adding an extra step, just duplicates the action.
Using Windows 10.

**Comment by spartanmartin** [comment] 2020-12-10 22:18
I am using Deckboard for it's MultiAction buttons in my daily workflow as well as in games such as Elite Dangerous.  I am also having this issue, but I can confirm that it is not limited to buttons like Shift, Ctrl, Alt, etc.  I'll give 2 examples:

Open several websites in a new window, then **close the blank tab**
**Run program** chrome.exe
**Open website** www.amazon.com
**Open website** www.bestbuy.com
**Delay** 500ms
**Keyboard Macro** CONTROL-TAB
**Keyboard Macro** CONTROL-W

Control gets "stuck", but so does tab and w.  If I were to type something immediately, CONTROL, TAB, and W would not be available until I have typed it once to "unstick" it.  The macro selects the empty tab, but because CONTROL is already engaged, it simulates a W instead of CONTROL-W, not closing the window as expected.  It does leave the W key engaged however.

In this case, since CONTROL is "stuck", using the mouse-wheel to scroll on the page (expected behavior) instead causes the page to zoom (expected behavior when using mouse-wheel with the CONTROL key pressed).  Manually pressing the CONTROL key "releases" the CONTROL key and the expected behavior resumes.

Another example with multiples of the same keypresses in a single MultiAction macro:

Request Docking in Elite Dangerous
**Keyboard Macro** 1  // Navigation Menu
**Delay** 500ms  // There is some input lag, so I'm waiting
**Keyboard Macro** E  // Navigate right in the submenus
**Keyboard Macro** E  // Navigation right in the submenus
...more keyboard macros, but it doesn't get that far due to the keys getting stuck.  I'll explain what I think is happening:

Again, the 1 and E keys are "stuck" and are not available for normal typing until I have manually typed them once to "unstick" them.  As a result, the second keyboard macro for the E keypress never fires since it's stuck.  Any number of simulated keypresses of the E button will not succeed until it is manually cleared.  Basically this makes every subsequent simulated keypress of any previous keypress fail.

**Comment by spartanmartin** [comment] 2020-12-10 23:07
As a follow up to my last post, I can simulate similar behavior from the first MultiAction macro regarding the keypress using the following Advanced Keyboard Macro.

Switch to blank tab and close tab (Advanced Keyboard Macro)
DOWN CONTROL
DOWN TAB
DOWN CONTROL
DOWN W

This switches to the blank tab and closes it.  However, we are left with the same unexpected behavior when using the mouse-wheel as before.  This leads me to believe that the MultiAction keyboard macros are actually performing **KeyDown** events instead of **KeyPress** events.

**Comment by rivafarabi** [comment] 2020-12-12 18:02
The fix for this issue is available in version [1.9.83](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.83)

**Closed by rivafarabi** 2020-12-12 18:02 UTC
Labels: bug
