### ISSUE TITLE
[BUG] Switch Board buttons do not work on Desktop App

### ISSUE THREAD

**Issue by DrewMasci** [rivafarabi/deckboard#842] opened 2022-03-18 18:07 UTC
**Describe the bug**
Using the Desktop app - Switch Board buttons do not switch the board.

**To Reproduce**
1. Create 2 boards, A & B
2. Create a Switch Board button on board A to link to board B
3. Press the Start button located toward the top of the app
4. Press the Switch Board button on board A
5. Nothing changes

**Expected behavior**
When I press a Switch Board button, I expect it to switch the board

**Screenshots**
N/A

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0

**Client App (please complete the following information):**
N/A

**Required files**
- [database.zip](https://github.com/rivafarabi/deckboard/files/8306693/database.zip)
- [log.log](https://github.com/rivafarabi/deckboard/files/8306703/log.log)

**Additional context**
n/a

**Comment by Corneloues** [comment] 2022-04-14 11:52
I get this behaviour too. Was about to report, but found this logged issue first.

**Comment by lendechy** [comment] 2022-06-04 20:29
Same issue here.

**Comment by c8501024** [comment] 2022-08-26 13:12
Same issue here. The issue is from March is something done here? Otherwise, I have to use another software.

**Comment by DrewMasci** [comment] 2022-09-11 23:42
> 

unfortunately the issue still persists

**Comment by rivafarabi** [comment] 2022-09-17 16:38
Fixed in [v2.0.5-rc3](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc3)

**Closed by rivafarabi** 2022-09-17 16:38 UTC
Labels: bug
