### ISSUE TITLE
[FEATURE REQUEST] Start minimized to system tray

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#550] opened 2020-11-07 10:42 UTC
When Deckboard runs at startup, the window appears, and you have to manually close it. It's very annoying.
Would've been great if Deckboard started minimized to the system tray.

**Comment by ZantsuRocks** [comment] 2020-11-08 14:30
Duplicate of #24

**Closed** 2020-11-10 14:38 UTC
Labels: feature request

**Comment by LoungeLizard65** [comment] 2024-04-04 11:24
Add this line to your batch file and it will simulate closing the window.  A timeout is added to let Deckboard fully start.  

powershell (ps Deckboard).CloseMainWindow()

Cheers.
